FROM swr.cn-central-221.ovaijisuan.com/wair/pytorch_2_0_0:pytorch_2.0.0-cuda_11.8.0-py_3.9-ubuntu_20.04

USER root

COPY ./requirements.txt /tmp/requirements.txt
RUN pip install pip -U -i https://mirrors.aliyun.com/pypi/simple/ \
    && pip install -r /tmp/requirements.txt -i https://mirrors.aliyun.com/pypi/simple/



COPY . /home/vllm/
RUN cp -rf /home/vllm/vllm/ /usr/local/python3.9.10/lib/python3.9/site-packages/

WORKDIR /home/server

# CMD ["python", "src/server.py"]
CMD ["bash", "run.sh"]
